
amqp-host=amq-broker-amqp-0-svc
amqp-port=5672
amqp-username=admin
amqp-password=admin
mp.messaging.incoming.incoming-events.connector=smallrye-amqp
mp.messaging.incoming.incoming-events.address=data.events
