
amqp-host=amq-broker-amqp-0-svc
amqp-port=5672
amqp-username=admin
amqp-password=admin
mp.messaging.incoming.incoming-events.connector=smallrye-amqp
mp.messaging.incoming.incoming-events.address=data.events

quarkus.openshift.build-strategy=binary
quarkus.kubernetes-client.trust-certs=true

# container e namespace
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.openshift.namespace=desafio-tam